
SELECT * FROM "SIA_ROLE_MAINT2"."T_PEQP_ZINC" WHERE CATEGORY NOT LIKE 'IMIS_PEQP_NOTEB';
DROP TABLE "SIA_ROLE_MAINT2"."T_PEQP_ZINC";
--Join table
CREATE COLUMN TABLE "SIA_ROLE_MAINT2"."T_PEQP_ZINC"("ID" NVARCHAR(100),"TEXT" NVARCHAR(2000),"CATEGORY" NVARCHAR(100),
													PRIMARY KEY ("ID"));
INSERT INTO "SIA_ROLE_MAINT2"."T_PEQP_ZINC"("ID", "TEXT", "CATEGORY")
SELECT "OBJECT_GUID","TEXT","SIA_ROLE_MAINT2"."T_ZINC_DESCRIPTION"."CATEGORY_ID"  from "SIA_ROLE_MAINT2"."T_PEQP_D" INNER
JOIN "SIA_ROLE_MAINT2"."T_ZINC_DESCRIPTION" ON 
"SIA_ROLE_MAINT2"."T_ZINC_DESCRIPTION"."OBJECT_GUID"="SIA_ROLE_MAINT2"."T_PEQP_D"."ID";
  
  select * from #IMIS_PEQP_MOBIL_ANDRD;
  SELECT * FROM #AB;
 drop table #IMIS_PEQP_NOTEB;
 --Procedure for splitting categories
 CALL "SIA_ROLE_MAINT2"."PROC_SPLIT_CATEGORY"('IMIS_PEQP_NOTEB,IMIS_PEQP_MOBIL_ANDRD,');
 DROP PROCEDURE "SIA_ROLE_MAINT2"."PROC_SPLIT_CATEGORY";
 CREATE PROCEDURE "SIA_ROLE_MAINT2"."PROC_SPLIT_CATEGORY"(IN CAT_DATA VARCHAR(4999))
 LANGUAGE SQLSCRIPT AS
 BEGIN
		DECLARE _TEXT NVARCHAR(100);
		DECLARE SPLITTED VARCHAR(4999);
		DECLARE CREATE_QR VARCHAR(4999);
		DECLARE INSERT_QR VARCHAR(4999);
		DECLARE INDEX INTEGER;
		_TEXT := :CAT_DATA;
		INDEX := 1;
		WHILE LOCATE(:_TEXT,',') > 0 DO
		SPLITTED:= SUBSTR_BEFORE(:_TEXT,',');
		CREATE_QR:='CREATE LOCAL TEMPORARY TABLE #'||:SPLITTED||'(ID NVARCHAR(500),TEXT NVARCHAR(500))';
    	EXEC CREATE_QR;
    	INSERT_QR:='INSERT INTO #'||:SPLITTED||' SELECT "ID","TEXT" FROM "SIA_ROLE_MAINT2"."T_PEQP_ZINC" 
    	    	    	    	    	WHERE "CATEGORY"='''||:SPLITTED||''';';
		_TEXT := SUBSTR_AFTER(:_TEXT,',');
		EXEC INSERT_QR;
		INDEX := :INDEX + 1;
		END WHILE;	
 END;


------------------------------------



       CALL "SIA_ROLE_MAINT2"."PROC_LDA_CAT"('IMIS_PEQP_NOTEB,IMIS_PEQP_MOBIL_ANDRD,');
DROP PROCEDURE "SIA_ROLE_MAINT2"."PROC_LDA_CAT";

CREATE PROCEDURE "SIA_ROLE_MAINT2"."PROC_LDA_CAT"(IN CAT_DATA VARCHAR(4999),IN T_TOPIC INTEGER,IN T_BURNIN INTEGER,
IN T_THIN INTEGER,IN T_ITERATION INTEGER,IN T_SEED INTEGER,IN T_ALPHA DECIMAL,IN T_MAX_TOP_WORDS INTEGER)
LANGUAGE SQLSCRIPT AS 
BEGIN 
DECLARE _TEXT NVARCHAR(100);
DECLARE T_NAME VARCHAR(500);
DECLARE SPLITTED VARCHAR(4999);
DECLARE CREATE_QR VARCHAR(4999);
DECLARE INSERT_QR VARCHAR(4999);
DECLARE INDEX INTEGER;
_TEXT := :CAT_DATA;
INDEX := 1;
WHILE LOCATE(:_TEXT,',') > 0 DO
SPLITTED:= SUBSTR_BEFORE(:_TEXT,',');
SELECT COUNT(*) INTO MY_ROW FROM "PUBLIC"."M_TABLES" WHERE table_name=:SPLITTED;
            IF (:MY_ROW > 0) THEN
            DROP_QR = 'DROP TABLE '||:SPLITTED||'';
            EXEC DROP_QR;
            END IF;
            CREATE_QR:='CREATE TABLE '||:SPLITTED||'(ID NVARCHAR(500),TEXT NVARCHAR(500))';
             EXEC CREATE_QR;
             INSERT_QR:='INSERT INTO '||:SPLITTED||' SELECT "ID","TEXT" FROM "SIA_ROLE_MAINT2"."T_PEQP_ZINC" 
                        WHERE "CATEGORY"='''||:SPLITTED||''';';
            _TEXT := SUBSTR_AFTER(:_TEXT,',');
            EXEC INSERT_QR;
DROP TABLE "SIA_ROLE_MAINT2"."LDA_T_DICTIONARY_PEQP_TBL";
CREATE COLUMN TABLE "SIA_ROLE_MAINT2"."LDA_T_DICTIONARY_PEQP_TBL" LIKE "SIA_ROLE_MAINT2"."DICTIONARY_T";
DROP TABLE "SIA_ROLE_MAINT2"."LDA_T_TOPICWORDDIST_PEQP_TBL";
CREATE COLUMN TABLE "SIA_ROLE_MAINT2"."LDA_T_TOPICWORDDIST_PEQP_TBL" LIKE "SIA_ROLE_MAINT2"."TOPICWORDDISTRIBUTION_T";
DROP TABLE "SIA_ROLE_MAINT2"."LDA_T_DOCTOPICDIST_PEQP_TBL";
CREATE COLUMN TABLE "SIA_ROLE_MAINT2"."LDA_T_DOCTOPICDIST_PEQP_TBL" LIKE "SIA_ROLE_MAINT2"."DOCTOPICDISTRIBUTION_T";
DROP TABLE "SIA_ROLE_MAINT2"."LDA_T_GENERALINFO_PEQP_TBL";
CREATE COLUMN TABLE "SIA_ROLE_MAINT2"."LDA_T_GENERALINFO_PEQP_TBL" LIKE "SIA_ROLE_MAINT2"."GENERALINFO_T";
DROP TABLE "SIA_ROLE_MAINT2"."LDA_T_TOPWORDS_PEQP_TBL";
CREATE COLUMN TABLE "SIA_ROLE_MAINT2"."LDA_T_TOPWORDS_PEQP_TBL" LIKE "SIA_ROLE_MAINT2"."TOPWORDS_T";
DROP TABLE "SIA_ROLE_MAINT2"."LDA_T_PARAMETERS_PEQP_TBL";
CREATE COLUMN TABLE "SIA_ROLE_MAINT2"."LDA_T_PARAMETERS_PEQP_TBL" LIKE "SIA_ROLE_MAINT2"."PARAMETERS_T";

-- populate the parameter table for running LDA on dataset 
INSERT  INTO "SIA_ROLE_MAINT2"."LDA_T_PARAMETERS_PEQP_TBL" VALUES ('TOPICS',:T_TOPIC,null,null);
INSERT  INTO "SIA_ROLE_MAINT2"."LDA_T_PARAMETERS_PEQP_TBL" VALUES ('BURNIN',:T_BURNIN,null,null);
INSERT INTO "SIA_ROLE_MAINT2"."LDA_T_PARAMETERS_PEQP_TBL" VALUES ('THIN',:T_THIN,null,null);
INSERT  INTO "SIA_ROLE_MAINT2"."LDA_T_PARAMETERS_PEQP_TBL" VALUES ('ITERATION',:T_ITERATION,null,null);
INSERT INTO "SIA_ROLE_MAINT2"."LDA_T_PARAMETERS_PEQP_TBL" VALUES ('SEED',:T_SEED,null,null);
INSERT  INTO "SIA_ROLE_MAINT2"."LDA_T_PARAMETERS_PEQP_TBL" VALUES ('ALPHA',null,:T_ALPHA,null);
INSERT INTO "SIA_ROLE_MAINT2"."LDA_T_PARAMETERS_PEQP_TBL" VALUES ('MAX_TOP_WORDS',:T_MAX_TOP_WORDS,null,null);
--Calling LDA estimate procedure
CALL "SIA_ROLE_MAINT2"."PAL_LDAESTIMATE_PEQP"(T_NAME,
       LDA_T_PARAMETERS_PEQP_TBL,
       LDA_T_DICTIONARY_PEQP_TBL,
       LDA_T_TOPICWORDDIST_PEQP_TBL,
       LDA_T_DOCTOPICDIST_PEQP_TBL,
       LDA_T_GENERALINFO_PEQP_TBL,
       LDA_T_TOPWORDS_PEQP_TBL) with overview;
INDEX := :INDEX + 1;
END WHILE;   
END;
