--Table statements
DROP TABLE DEMO_TBL;
CREATE TABLE DEMO_TBL(ID INTEGER PRIMARY KEY,VALUE VARCHAR(20));

DROP PROCEDURE "PROC_EXCEPTIONS";
CREATE PROCEDURE "PROC_EXCEPTIONS"(
IN ID INTEGER,IN DETAILS VARCHAR(4999),OUT EX_MESSAGE VARCHAR(4999))
LANGUAGE SQLSCRIPT AS
BEGIN
	DECLARE QR VARCHAR(4999);
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		IF ::SQL_ERROR_CODE='274' THEN
	  	EX_MESSAGE := 'Sorry the Error message is: '||::SQL_ERROR_MESSAGE;
	  	ELSEIF ::SQL_ERROR_CODE='301' THEN
	  	EX_MESSAGE := ' ' ||::SQL_ERROR_CODE || ' : '||::SQL_ERROR_MESSAGE;
	  	ELSE 
	  	EX_MESSAGE := 'Unrecognized error';
	  	END IF;
	END;
	QR:='INSERT INTO "DEMO_TBL" VALUES('||:ID||','''||:DETAILS||''')';
	EXEC QR;
	EX_MESSAGE := 'Product "' || :ID || '" inserted successfully'; 
END;
CALL PROC_EXCEPTIONS(89,'FD',?);
