DROP PROCEDURE "SIA_ROLE_MAINT2"."PROC_RELATED_DOC";
CREATE PROCEDURE "SIA_ROLE_MAINT2"."PROC_RELATED_DOC"(IN DOC_NAME NVARCHAR(500),OUT FINAL_TABLE OUTPUT_T_RELATED_DOCS)
LANGUAGE SQLSCRIPT AS 
BEGIN
	   DECLARE DOC NVARCHAR(500);
	   DOC:=DOC_NAME;
       EXEC 'INSERT INTO "SIA_ROLE_MAINT2"."OUTPUT_TEMP_RELATED_DOCS" select T.
       "RUNID",T."TEXT",T.TOTAL_TERM_COUNT, T.SCORE
	   FROM TM_GET_RELATED_DOCUMENTS (
	   DOCUMENT '''||:DOC||'''
       SEARCH  "TEXT"
       FROM "SIA_ROLE_MAINT2"."T_TOPWORDS_COM_TBL"
       RETURN
       TOP 5 
       RUNID,TEXT
   	   ) AS T';
   	   FINAL_TABLE= SELECT * FROM "SIA_ROLE_MAINT2"."OUTPUT_TEMP_RELATED_DOCS";
END;
CALL "SIA_ROLE_MAINT2"."PROC_RELATED_DOC"('SOFTWARE',?);
CREATE COLUMN TABLE "SIA_ROLE_MAINT2"."OUTPUT_TEMP_RELATED_DOCS" LIKE "SIA_ROLE_MAINT2"."OUTPUT_T_RELATED_DOCS";
CREATE TYPE "SIA_ROLE_MAINT2"."OUTPUT_T_RELATED_DOCS" AS TABLE (
	 "RUNID" NVARCHAR(500),
	 "TEXT" NVARCHAR(500),
	 "TOTAL_TERM_COUNT" INTEGER,
	 "SCORE" DOUBLE ) ;
DROP TYPE "SIA_ROLE_MAINT2"."OUTPUT_T_RELATED_DOCS"
CREATE COLUMN TABLE "SIA_ROLE_MAINT2"."T_OO" LIKE "OUTPUT_T_RELATED_DOCS";